package rfi.monpaniervert.security;

public enum AuthentificationError {

	CONCURRENT_ACCESS, 
	ACCOUNT_BLOCKED, 
	BAD_CREDENTIALS, 
	BAD_PASSWORD, 
	ACCOUNT_DEACTIVATED,
	AUTHENTICATION_REQUIRED,
	NO_RIGHTS, 
	EMAIL_EXISTING

}
