package rfi.monpaniervert.enums;

public enum ECategorie {

	BOUCHERIE_VOLAILLE_POISSONNERIE, LAITIERS_OEUFS_VEGETAL, FRUITS_LEGUMES, EPICERIE_SUCREES, EPICERIE_SALEE, BOISSONS, ANIMALERIE, CHARCUTERIE_TRAITEUR_PAIN
}
