package rfi.monpaniervert.enums;

public enum ECategorie {

	POISSONNERIE, BOUCHERIE, FRUITS_LEGUMES, CHARCUTERIE, FROMAGE, BOISSONS, ANIMALERIE, VOLAILLE, BOULANGERIE, PATISSERIE, TRAITEUR_ROTISERIE
}
