package rfi.monpaniervert.enums;

public enum ESSCategorie {

	  /** BOUCHERIE **/
	  BOEUF, VEAU, PORC, AGNEAU,

	  /** POISSONNERIE **/
	  FRUITS_MER, POISSON, SUSHI,

	  /** CHARCUTERIE **/
	  PLATEAU_CHARCUTERIE, JAMBON, SAUCISSON, PATE_TERRINE,

	  /** FROMAGE **/
	  PLATEAU_FROMAGE, FROMAGE_VACHE, FROMAGE_CHEVRE, FROMAGE_BREBIS, FROMAGE,

	  /** VOLAILLE **/
	  POULET, LAPIN, DINDE, CAILLE, FOIE_GRAS, CANARD,

	  /** BOULANGERIE **/
	  PAIN, VIENNOISERIE,

	  /** PATISSERIE **/
	  GATEAUX, TARTES, MIGNARDISES,
	  
	  /** TRAITEUR_ROTISERIE **/
	  SALADE, PIZZA, POULET_ROTI, ACCOMPAGNEMENT, PLAT_CHAUD
}
