package rfi.monpaniervert.enums;

public enum ETypeEmail {
	CREATION_COMPTE,
	DESACTIVATION_COMPTE,
	SUPPRESSION_COMPTE,
	
	CREATION_COMPAGNIE,
	SUPPRESSION_COMPAGNIE,
	
	COMMANDE_EN_COURS,
	COMMANDE_ERROR,
	COMMANDE_VALIDE,
	COMMANDE_INFORMATION} 
